### PR TITLE
made README.md better

### PR DESCRIPTION
**Pull request by Compdog-inc**
:)

### CODE REVIEW

**Review by Compdog-inc — COMMENTED** [review]
good

**Comment by Compdog-inc** [comment]
merge now!!

**Comment by Compdog-inc** [comment]
@Wers200 MERGE

**Comment by Compdog-inc** [comment]
#1 @Wers200 
Duplicate of #1 

- [ ] f
- [x] a
- [x] s
- [ ] c
- [x] fe
- [x] f

> 

> 

> 

> 

> 

> 

> 

>

**Comment by Wers200** [comment]
AHAHAHHAHAHAHAHAHAHAHAHAHAHHAHAHAHAHAHAHHA

**Comment by Compdog-inc** [comment]
@Wers200 so will you merge?

**Comment by Wers200** [comment]
I CANT STOP LAUGHING

**Comment by Compdog-inc** [comment]
so merge

**Comment by Compdog-inc** [comment]
it will be better

**Comment by Compdog-inc** [comment]
#2

**Comment by Compdog-inc** [comment]
yay

**Pull request merged**
